baseURL = 'https://www.bekapod.dev/'
languageCode = 'en-gb'
title = 'Becky Jones'
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term']
sectionPagesMenu = 'main'

[Params]
  description = 'Frontend developer, serial hobby app builder and crafter'

[Params.social]
  github = 'https://github.com/bekapod'
  linkedin = 'https://www.linkedin.com/in/rebekah-jones-b3622a40/'
  twitter = 'https://twitter.com/bekapod'